#+BEGIN_COMMENT
.. title: About Me
.. slug: about-me
.. date: 2019-12-26 22:35:28 UTC
.. tags:
.. category:
.. link:
.. description:
.. type: text
.. nocomments: true
#+END_COMMENT

* About Me
I'm Oisín,

A longtime hobbyist game-developer, juggler, and machine learning enthusiast, recently I've
been trying to up my pure-maths skills, too. I now work part time as a researcher at the Adapt Center,
work as a contract game-developer and try to balance up some other projects on the side!

This site collects random projects I've been working on in my spare time.

You may be interested in my  [[../pages/freelance/][Freelance Page]] too!

** Misc
Other bits I've worked on/am working on include:
- [[https://syze.ai/][*Syze.ai*]]: An AI-based startup aiming to reduce returns for online clothing stores.
- [[https://www.facebook.com/WizardLizardGame/][*WizardLizard*]]: A 3d puzzle game based on illusions, featuring a procedural lizard.

[[../misc/resume.pdf][My CV]] is a bit outdated now but might be interesting!


* Contact
Feel free to contact me via email; hi@imois.in. Also, I'm told there are people
sharing my name/background on linkedin but they're not me(!)
