version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: test
          command: npm run test:cov
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: dist
          destination: dist
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: ./build/test-results.xml
workflows:
  version: 2
  build:
    jobs:
      - build:
          # All branches, all tags.
          filters:
            tags:
              only: /.*/
