#+BEGIN_COMMENT
.. title: Learning The Properties of a Fair 3-Sided Coin
.. slug: learning-a-fair-3-sided-dice
.. date: 2020-08-23 22:30:01 UTC+01:00
.. tags:
.. category: math
.. link:
.. has_math: true
.. description:
.. type: text
.. status: draft
#+END_COMMENT

* Intro
#+BEGIN_EXPORT html
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/oimo/1.0.9/oimo.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/three.js/101/three.min.js"></script>
#+END_EXPORT

A coin effectively has 2 sides, heads or tails. Still, there's a chance --- albeit small --- that the coin can land on it's edge. This begs the question, how 'thick' should a coin be so that
it has equal chances of landing on any of the 3 sides (Heads, Tails, or Edge).

I learned about this problem in [[https://www.youtube.com/watch?v=-qqPKKOU-yY][this video by Matt Parker]], who looks at some mathematical ways to solve it. The approaches don't line up with my intuition though; estimating that a standard euro coin would fall on it's edge $1/20$ times ($P(E) \approx 0.0501$) via the 'sphere method', or $1/16$ via the 'triangle method' ($P(E) \approx 0.064$).

Instead of relying on maths or 'thinking' (pfft), why not just simulate it? We can vary the widths of coins, their coefficients of restitution, starting heights and velocities and see how that affects our results too.

#+BEGIN_EXPORT html
<div class="figure">

    <canvas id="physics-sim" class="light_border" width="600" height="600"> Your browser sucks :c. </canvas>

    <span style="display:flex; padding-bottom:20px">
    <div id="num_heads_box" class="stacked_bar_chart" style=" background:#ffa324">
    #Heads:&nbsp;<b id="num_heads_val">0</b>
    </div>
    <div id="num_tails_box" class="stacked_bar_chart" style="background:#ff4546">
    #Tails:&nbsp;<b id="num_tails_val">0</b>
    </div>
    <div id="num_sides_box" class="stacked_bar_chart" style="background:#48abf0">
    #Sides:&nbsp;<b id="num_sides_val">0</b>
    </div>

    </span>

    <!-- Sliders -->
    <span class="slider_row">
        <span class="slider_label">Coin Thickness</span>
        <span id="coin_width" class="flat-slider"></span>
        <span type="text" id="coin_width_val" class="slider_text"></span>
    </span>
    <span class="slider_row">
        <span class="slider_label">Restitution (Bounce)</span>
        <span id="coin_bounce" class="flat-slider"></span>
        <span type="text" id="coin_bounce_val" class="slider_text"></span>
    </span>
    <span class="slider_row">
        <span class="slider_label">Maximum Throw Spin</span>
        <span id="throw_spin" class="flat-slider"></span>
        <span type="text" id="throw_spin_val" class="slider_text"></span>
    </span>
    <span class="slider_row">
        <span class="slider_label">Drop Height</span>
        <span id="throw_height" class="flat-slider"></span>
        <span type="text" id="throw_height_val" class="slider_text"></span>
    </span>

    <span class="slider_row">
        <span class="slider_label">Num Coins <b>x</b></span>
        <span id="num_coins_x" class="flat-slider"></span>
        <span type="text" id="num_coins_x_val" class="slider_text"></span>
    </span>

    <span class="slider_row">
        <span class="slider_label">Num Coins <b>y</b></span>
        <span id="num_coins_y" class="flat-slider"></span>
        <span type="text" id="num_coins_y_val" class="slider_text"></span>
    </span>

    <div id='interface'>
        <input type="button" value="Reset Counters" onClick=reset_counts()>
        <input type="button" value="Restart Simulation" onClick=populate()>
    </div>
</div>
<script src="../assets/js/3_sided_coin/PhysicsSim.js"></script>
#+END_EXPORT

#+BEGIN_SRC inline-js
{
    $("#coin_width").slider({
        // 10x the ratio of the diameter
        min: 10,
        max: 2000,
        values: [coin_thickness*100],
        slide: function(event, ui) {
            $("#coin_width_val").text(ui.values[0]/100.0);
            coin_thickness = ui.values[0]/100.0;
        },
    });
    $("#coin_width_val").text(coin_thickness);

    $("#coin_bounce").slider({
        min: 10,
        max: 80,
        values: [coin_bounce*100],
        slide: function(event, ui) {
            $("#coin_bounce_val").text(ui.values[0]/100.0);
            coin_bounce = ui.values[0]/100.0;
        },
    });
    $("#coin_bounce_val").text(coin_bounce);

    $("#throw_spin").slider({
        min: 5,
        max: 40,
        values: [throw_spin],
        slide: function(event, ui) {
            $("#throw_spin_val").text(ui.values[0]);
            throw_spin = ui.values[0];
        },
    });
    $("#throw_spin_val").text(throw_spin);

    $("#throw_height").slider({
        min: 10,
        max: 500,
        values: [throw_height],
        slide: function(event, ui) {
            $("#throw_height_val").text(ui.values[0]);
            throw_spin = ui.values[0];
        },
    });
    $("#throw_height_val").text(throw_height);

    // slider
    $("#num_coins_x").slider({
        min: 1,
        max: 12,
        values: [num_coins_x],
        slide: function(event, ui) {
            $("#num_coins_x_val").text(ui.values[0]);
            num_coins_x = ui.values[0];
        },
    });
    $("#num_coins_x_val").text(num_coins_x);

    $("#num_coins_y").slider({
        min: 1,
        max: 12,
        values: [num_coins_y],
        slide: function(event, ui) {
            $("#num_coins_y_val").text(ui.values[0]);
            num_coins_y = ui.values[0];
        }
    });
    $("#num_coins_y_val").text(num_coins_y);
}
#+END_SRC
